### ISSUE TITLE
Vamos a mejorar el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-silviademiguel7#1]
Venga @silviademiguel7, vamos a apañarlo !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa propTypes para comprobar el tipo de dato de las props SOLO EN LOS COMPONENTES QUE RECIBEN PROPS
- [x] El tema del indentado tienes que resolverlo, ya no va a haber más recordatorios en el curso y esto necesitas tenerlo en cuenta porque tu código es bueno pero si parece descuidado va a parecer peor de lo que es.
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by silviademiguel7** [comment]
I have fixed my proyect and done the optional part

**Comment by oneeyedman** [comment]
Ole!
